version: '3'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_earthquake
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3310:3310"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_frogmi
    command: ['bash', '-c', 'rails db:migrate --trace && rails s']
    ports:
      - "3000:3000"
    volumes:
      - .:/rails

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: cron_frogmi
    command: ['bash', '-c', 'bundle exec rake earthquake:earthquakes_data_service && whenever --update-crontab --set environment=production && cron -f']
    volumes:
      - .:/rails
    depends_on:
      - web
